import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextjsProvider from "@/provider/NextjsProvider";

const poopins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextjsProvider>
      <html lang="en">
        <body className={`${poopins.className} antialiased`}>
          <header className="py-2 md:w-11/12 mx-auto">
            <Navbar />
          </header>

          <main className="py-2 md:w-11/12 mx-auto">{children}</main>

          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextjsProvider>
  );
}
